# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_acc/design_acc.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_acc || ORIG_REF_NAME==design_acc} -quiet] -quiet

# IP: bd/design_acc/ip/design_acc_processing_system7_0_0/design_acc_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_acc_processing_system7_0_0 || ORIG_REF_NAME==design_acc_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_acc/ip/design_acc_cordic_ip_0_0/design_acc_cordic_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_acc_cordic_ip_0_0 || ORIG_REF_NAME==design_acc_cordic_ip_0_0} -quiet] -quiet

# IP: bd/design_acc/ip/design_acc_auto_pc_0/design_acc_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_acc_auto_pc_0 || ORIG_REF_NAME==design_acc_auto_pc_0} -quiet] -quiet

# IP: bd/design_acc/ip/design_acc_ps7_0_axi_periph_0/design_acc_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_acc_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_acc_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_acc/ip/design_acc_rst_ps7_0_100M_0/design_acc_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_acc_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_acc_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: bd/design_acc/design_acc_ooc.xdc
