# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/stream_acc_design/stream_acc_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==stream_acc_design || ORIG_REF_NAME==stream_acc_design} -quiet] -quiet

# IP: bd/stream_acc_design/ip/stream_acc_design_cordic_stream_acc_0_0/stream_acc_design_cordic_stream_acc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==stream_acc_design_cordic_stream_acc_0_0 || ORIG_REF_NAME==stream_acc_design_cordic_stream_acc_0_0} -quiet] -quiet

# IP: bd/stream_acc_design/ip/stream_acc_design_axi_fifo_mm_s_0_0/stream_acc_design_axi_fifo_mm_s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==stream_acc_design_axi_fifo_mm_s_0_0 || ORIG_REF_NAME==stream_acc_design_axi_fifo_mm_s_0_0} -quiet] -quiet

# IP: bd/stream_acc_design/ip/stream_acc_design_processing_system7_0_0/stream_acc_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==stream_acc_design_processing_system7_0_0 || ORIG_REF_NAME==stream_acc_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/stream_acc_design/ip/stream_acc_design_rst_ps7_0_100M_0/stream_acc_design_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==stream_acc_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==stream_acc_design_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/stream_acc_design/ip/stream_acc_design_ps7_0_axi_periph_0/stream_acc_design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==stream_acc_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==stream_acc_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/stream_acc_design/ip/stream_acc_design_auto_pc_0/stream_acc_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==stream_acc_design_auto_pc_0 || ORIG_REF_NAME==stream_acc_design_auto_pc_0} -quiet] -quiet

# XDC: bd/stream_acc_design/stream_acc_design_ooc.xdc
