# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Mateusz/Desktop/Magisterka_semestr_1/SDUP/repo/SDUP/lab5_arm_pipeline/stream_acc_system/stream_acc_system.srcs/sources_1/bd/stream_acc_design/ip/stream_acc_design_auto_pc_0/stream_acc_design_auto_pc_0.xci
# IP: The module: 'stream_acc_design_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Mateusz/Desktop/Magisterka_semestr_1/SDUP/repo/SDUP/lab5_arm_pipeline/stream_acc_system/stream_acc_system.srcs/sources_1/bd/stream_acc_design/ip/stream_acc_design_auto_pc_0/stream_acc_design_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'stream_acc_design_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/Mateusz/Desktop/Magisterka_semestr_1/SDUP/repo/SDUP/lab5_arm_pipeline/stream_acc_system/stream_acc_system.srcs/sources_1/bd/stream_acc_design/ip/stream_acc_design_auto_pc_0/stream_acc_design_auto_pc_0.xci
# IP: The module: 'stream_acc_design_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Mateusz/Desktop/Magisterka_semestr_1/SDUP/repo/SDUP/lab5_arm_pipeline/stream_acc_system/stream_acc_system.srcs/sources_1/bd/stream_acc_design/ip/stream_acc_design_auto_pc_0/stream_acc_design_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'stream_acc_design_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
